# Environment values: Development
replicaCount: 1

autoscaling:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

podDisruptionBudget:
  enabled: false
