services:
  frontend:
    build:
      context: ./applications/frontend
      dockerfile: Dockerfile
      target: dev
    container_name: pokemon-frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
  backend:
    build:
      context: ./applications/api
      dockerfile: Dockerfile
    container_name: pokemon-backend
    ports:
      - 3005:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
