const pokemonSchema = `create table public.pokemons (
  abilities text null,
  against_bug double precision null,
  against_dark double precision null,
  against_dragon double precision null,
  against_electric double precision null,
  against_fairy double precision null,
  against_fight double precision null,
  against_fire double precision null,
  against_flying double precision null,
  against_ghost double precision null,
  against_grass double precision null,
  against_ground double precision null,
  against_ice double precision null,
  against_normal double precision null,
  against_poison double precision null,
  against_psychic double precision null,
  against_rock double precision null,
  against_steel double precision null,
  against_water double precision null,
  attack bigint null,
  base_egg_steps bigint null,
  base_happiness bigint null,
  base_total bigint null,
  capture_rate text null,
  classfication text null,
  defense bigint null,
  experience_growth bigint null,
  height_m double precision null,
  hp bigint null,
  japanese_name text not null,
  name text not null,
  percentage_male double precision null,
  pokedex_number bigint null,
  sp_attack bigint null,
  sp_defense bigint null,
  speed bigint null,
  type1 text null,
  type2 text null,
  weight_kg double precision null,
  generation bigint null,
  is_legendary bigint null,
  constraint cats_pkey primary key (japanese_name, name)
) TABLESPACE pg_default;`;
export default pokemonSchema;
