apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/dipak-01/Multi-Cluster-Kubernetes-Platform.git
    targetRevision: main
    path: helm/api
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
      parameters:
        - name: image.repository
          value: platform-api
        - name: image.tag
          value: "1.0.0"
        - name: image.pullPolicy
          value: Never
        - name: secretEnv.DATABASE_URL
          value: "postgresql://postgres.nxrzxqpopwofcdxjsogn:aylljgUddaAlN6af@aws-0-ap-south-1.pooler.supabase.com:5432/postgres"
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/dipak-01/Multi-Cluster-Kubernetes-Platform.git
    targetRevision: main
    path: helm/frontend
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
      parameters:
        - name: image.repository
          value: platform-frontend
        - name: image.tag
          value: "1.0.0"
        - name: image.pullPolicy
          value: Never
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
